### ISSUE TITLE
Invalid Application-ID or API

### ISSUE THREAD

**Issue by webecks** [w3bdesign/wp-algolia-woo-indexer#181]
It's follow up from  #175.

Previously I followed your advice, and it worked fine when I used the free plan (BUILD).
Then my client asked to switch to a PREMIUM plan, and the problem in #175  happened again.

Are **Admin API Key** and **Write API Ke**y the same?

![Screenshot 2023-05-13 084332](https://github.com/w3bdesign/wp-algolia-woo-indexer/assets/18439793/ea026892-172e-4e6e-b9ff-11539f2db2a9)
![Screenshot 2023-05-13 083440](https://github.com/w3bdesign/wp-algolia-woo-indexer/assets/18439793/79961e60-34d6-4a41-93a5-cd4a6edb51a9)

**Comment by w3bdesign** [comment]
@webecks 

I believe admin API key is the "Write API key", but I have never used the plugin with a premium plan, so I am unable to test myself.

**Comment by w3bdesign** [comment]
You use the "Search API" key in the frontend part of the application.

**Comment by webecks** [comment]
> You use the "Search API" key in the frontend part of the application.

Yes, I aware of that. With free plan, it's working fine. Only when I change to a premium plan, the error occurs when sending the product to algolia.

**Comment by w3bdesign** [comment]
@webecks 

I only have access to the free version, but I guess you could temporarily hardcode the API key if you open /classes/class-algolia-woo-indexer.php and locate the function public static function update_settings_options()

There you can change the $sanitized_api_key to this:

$sanitized_api_key = "enteryourlivekeyhere";

It's not the best option, but it should in theory allow you to use the premium version for now. 

I am attaching a screenshot below.


![image](https://github.com/w3bdesign/wp-algolia-woo-indexer/assets/45217974/ebf9fdd4-d682-4bfa-afd5-d318dc11e98d)

**Comment by w3bdesign** [comment]
@webecks 

You'd probably get a better response if you posted the issue in https://github.com/algolia/algoliasearch-client-php

**Comment by webecks** [comment]
@w3bdesign just want to update, I can send product to algolia using premium account after commenting
`self::can_connect_to_algolia();` (`classes/class-send-products.php:L226`)

I'm using version 1.0.5.
I checked on version 1.0.6 (https://github.com/w3bdesign/wp-algolia-woo-indexer/blob/master/classes/class-send-products.php#L150)

**Comment by w3bdesign** [comment]
> @w3bdesign just want to update, I can send product to algolia using premium account after commenting `self::can_connect_to_algolia();` (`classes/class-send-products.php:L226`)
> 
> I'm using version 1.0.5. I checked on version 1.0.6 (https://github.com/w3bdesign/wp-algolia-woo-indexer/blob/master/classes/class-send-products.php#L150)

@webecks 

I released https://github.com/w3bdesign/wp-algolia-woo-indexer/releases/tag/1.0.7 which changed the wp_die() to just a warning that can be dismissed, as I currently don't have a way to test with the premium version, can you verify if it works better now?

**Comment by webecks** [comment]
@w3bdesign unfortunately not, still error.
error still in the same place, `send_products_to_algolia()`

here's debug stack's trace:
```
[20-May-2023 04:26:05 UTC] PHP Fatal error:  Uncaught Algolia\AlgoliaSearch\Exceptions\BadRequestException: Invalid Application-ID or API key in /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210
Stack trace:
#0 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(158): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->handleResponse()
#1 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php(78): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->request()
#2 /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/SearchClient.php(205): Algolia\AlgoliaSearch\RetryStrategy\ApiWrapper->read()
#3 /path/wp-content/plugins/algolia-woo-indexer/classes/class-send-products.php(71): Algolia\AlgoliaSearch\SearchClient->listApiKeys()
#4 /path/wp-content/plugins/algolia-woo-indexer/classes/class-send-products.php(150): Algowoo\Algolia_Send_Products::can_connect_to_algolia()
#5 /path/wp-content/plugins/algolia-woo-indexer/classes/class-algolia-woo-indexer.php(211): Algowoo\Algolia_Send_Products::send_products_to_algolia()
#6 /path/wp-includes/class-wp-hook.php(308): Algowoo\Algolia_Woo_Indexer::maybe_send_products()
#7 /path/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /path/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /path/wp-admin/admin.php(175): do_action()
#10 /path/wp-admin/options-general.php(10): require_once('...')
#11 {main}
  thrown in /path/wp-content/plugins/algolia-woo-indexer/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php on line 210
```

**Comment by w3bdesign** [comment]
> Invalid Application-ID or API key

OK, I can code a better fix for this later, for now, at least you know how to use the plugin with Premium.
